### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wolejnr**
A few updates to the setup documentation

### CODE REVIEW

**Comment by gbozee** [comment]
Please the readme doesn't seem to reflect changes from the develop branch?

**Comment by wolejnr** [comment]
Oops!! I used the `master` instead of the `develop` branch. I will correct that

**Comment by gbozee** [comment]
Please what's d progress on this merge request?

**Comment by wolejnr** [comment]
I have created another pull request #18

**Comment by gbozee** [comment]
The spacing seems to be off when viewing the readme from github 
image

**Comment by gbozee** [comment]
If you are more familiar with markdown, that should be used instead of rst.

**Pull request closed without merging**
